# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.117.59.156:3306/spring_boot_learn?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Lt199606.

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug